### ISSUE TITLE
realType can't input non-english character

### ISSUE THREAD

**Issue by RainOfPhone** [dmtrKovalenko/cypress-real-events#290]
I found that cy.realType cound only type character in keyboard into input. Those character Such as {selectAll} or non-english character can't be typed into input by this method.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/29797975/184060741-5d0962e2-5192-4731-9cac-6a6682f23b8d.png">

**Comment by kahboom** [comment]
Yeah I'm getting the same for `{selectAll}`

**Comment by dmtrKovalenko** [comment]
That's happening because we can not maintain all the key codes for all Unicode characters. 

If you have a really hard need to use this instead of cypress event you can try to modify our keycode definition file or add an api to pass custom definitions. 

Another option will be to implement the setText from the chrome engine.

**Comment by dmtrKovalenko** [comment]
The `{selectAll}` is not a key it's a weird command so not sure we will integrate it here. 

But maybe, idk
