### ISSUE TITLE
Add 'clear()' or '{selectAll}{backspace}' for realType()

### ISSUE THREAD

**Issue by AustinBernerEvercast** [dmtrKovalenko/cypress-real-events#383]
The web application I'm working with requires me to use realType() for the user action instead of the cypress default. 

the .clear() method doesn't work when applied before the realType() method, so I tried the following to no avail:

`.realType('{selectAll}{backspace}')`

I get the following error in the Cypress runner:

`Unrecognized character "{selectAll}".`

Please add this functionality when possible - I'm attempting workarounds but haven't found an option yet

**Comment by dmtrKovalenko** [comment]
I don't think we will add it because we are trying to be as simple a provider of native events as possible.  

If you want to test type clearing only using real events you can do this:

```ts
    cy.realType("lalalalala");
    cy.get("input[name=q]").realClick({ clickCount: 3 });
    cy.realPress("Backspace");
```

You can also make your own custom command based on this. Or instead of triple click you can simply do `cy.type("{selectall}")` it will be the same as pupetter community is doing for selection

**Comment by AustinBernerEvercast** [comment]
Thank you @dmtrKovalenko , the triple click is a great idea that I had not thought of before. Great workaround, thank you!
